[package]
name = "renderer"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
api = { workspace = true }
bevy = { version = "0.18.1", default-features = false, features = ["3d"] }
chrono = { workspace = true }
console_error_panic_hook = "0.1.7"
serde_json = { workspace = true }
serde-wasm-bindgen = "0.6.5"
uuid = { workspace = true }
wasm-bindgen = "0.2.128"
futures = "0.3.34"
wasm-bindgen-futures = "0.4.78"

[package.metadata.wasm-pack.profile.release]
wasm-opt = ["-Os"]
